apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: angela-hpa-1
  namespace: teste
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: angela-deployment-1
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
