apiVersion: v1
kind: Service
metadata:
  name: angela-deployment-service-1
  namespace: teste
  labels:
    app: angela-api-1
spec:
  type: LoadBalancer
  ports:
  - port: 80            # Porta exposta do Service
    targetPort: 8080    # Porta do container
  selector:
    app: angela-api-1    # Seleciona os Pods do Deployment
