apiVersion: v1
kind: Service
metadata:
  name: angela-deployment-service-1
  namespace: teste
  labels:
    app: angela-api-1
spec:
  type: LoadBalancer
  ports:
  - port: 80          
    targetPort: 8080   
  selector:
    app: angela-api-1    
