name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - TesteMB/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . --tag hello-world:latest
          
      - name: Run Ruby script with timeout
        run: |
          timeout 10s docker run --rm hello-world:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build  # Dependência do job build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
