name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - TesteMB/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . --tag hello-world:latest

      - name: Run tests
        run: |
          docker run hello-world:latest pytest  
